version: '3'
services:
  dev:
    image: atcoder-pyenv
    container_name: atcoder-pyenv-conrainer

    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    
    volumes:
      - .:/workspace:cached
      - ~/.zshrc:/root/.zshrc
      - ~/.vimrc:/root/.vimrc
      - ~/.gitconfig:/root/.gitconfig
    
    tty: true
    command: /bin/sh -c "while sleep 1000; do :; done"
